@set allusersprofile=c:\programdata
@set android_sdk_root=f:\android\sdk
@set ant_root=f:\apache-ant-1.9.5\bin
@set appdata=c:\users\administrator\appdata\roaming
@set catalina_home=f:\tomcat9.0
@set cocos_console_root=d:\cocos\cocos2d-x\cocos2d-x-3.10\tools\cocos2d-console\bin
@set cocos_templates_root=d:\cocos\cocos2d-x\cocos2d-x-3.10\templates
@set cocos_x_root=d:\cocos\cocos2d-x
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=linyuenan
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=d:\vs2013\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows\v8.1\extensionsdks
@set fp_no_host_check=no
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\3.1\framework\v4.0\
@set gtk_basepath=c:\program files (x86)\gtksharp\2.12\
@set home=d:\emacs
@set homedrive=c:
@set homepath=\users\administrator
@set include=d:\vs2013\vc\include;d:\vs2013\vc\atlmfc\include;c:\program files (x86)\windows kits\8.1\include\shared;c:\program files (x86)\windows kits\8.1\include\um;c:\program files (x86)\windows kits\8.1\include\winrt
@set java_home=d:\java
@set kbe_bin_path=e:\kbengine-0.9.12/kbe/bin/server/
@set kbe_res_path=e:\kbengine-0.9.12/kbe/res;e:\kbengine-0.9.12/assets/;e:\kbengine-0.9.12/assets/scripts;e:\kbengine-0.9.12/assets/res/
@set kbe_root=e:\kbengine-0.9.12
@set lib=d:\vs2013\vc\lib;d:\vs2013\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;d:\vs2013\vc\lib;d:\vs2013\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;c:\program files (x86)\microsoft sdks\windows\v8.1\extensionsdks\microsoft.vclibs\12.0\references\commonconfiguration\neutral
@set localappdata=c:\users\administrator\appdata\local
@set logonserver=\\linyuenan
@set lua_dev=d:\lua\5.1
@set lua_path=d:\lua\5.1\lua\?.luac
@set moz_plugin_path=d:\foxit reader\plugins\
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\msbuild\sdks
@set msbuild_exe_path=d:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set ndk_root=f:\android-ndk-r10d
@set number_of_processors=4
@set os=windows_nt
@set path=d:\vs2013\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft sdks\f#\3.1\framework\v4.0\;c:\program files (x86)\msbuild\12.0\bin;d:\vs2013\common7\ide\;d:\vs2013\vc\bin;d:\vs2013\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;d:\vs2013\vc\vcpackages;c:\program files (x86)\html help workshop;d:\vs2013\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\;d:\vs2013\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries/x86;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files (x86)\gtksharp\2.12\bin;d:\python;c:\program files\tortoisesvn\bin;f:\tomcat9.0\bin;f:\tomcat9.0\lib;d:\xoreax\incredibuild;d:\mingw\bin;f:\android-ndk-r10d;d:\lua\5.1;d:\lua\5.1\clibs;f:\android\sdk\platform-tools;f:\android\sdk\build-tools\19.1.0;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;d:\cocos\tools\ant\bin;d:\program files (x86)\git\cmd;d:\cocos\cocos2d-x\cocos2d-x-3.10\templates;d:\cocos\cocos2d-x\cocos2d-x-3.10\tools\cocos2d-console\bin;d:\java\bin;d:\microsoft vs code\bin;c:\users\administrator\appdata\local\githubdesktop\bin;d:\program files\microsoft vs code\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc;.wlua;.lexe
@set pkgdefapplicationconfigfile=c:\users\administrator\appdata\local\microsoft\visualstudio\12.0\devenv.exe.config
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 60 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=3c03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\msbuild\
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\admini~1\appdata\local\temp
@set tmp=c:\users\admini~1\appdata\local\temp
@set tomcat_home=f:\tomcat9.0
@set uid=1994
@set userdomain=linyuenan
@set username=administrator
@set userprofile=c:\users\administrator
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcinstalldir=d:\vs2013\vc\
@set visualstudiodir=c:\users\administrator\documents\visual studio 2013
@set visualstudioedition=microsoft visual studio ultimate 2013
@set visualstudioversion=12.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=d:\vs2013\common7\tools\
@set vsinstalldir=d:\vs2013\
@set vslang=2052
@set windir=c:\windows
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\
@set windows_tracing_flags=3
@set windows_tracing_logfile=c:\bvtbin\tests\installpackage\csilogfile.log

@call "d:\Program Files (x86)\PVS-Studio\x86\clang.exe" --driver-mode=cl @"E:\shawnNan\OpenGLTest\Simple OpenGL Image Library\projects\VC9\image_DXT.c.PVS-Studio.preprocess.cmd.rsp" 2>&1